# Propriedades para quando rodar os testes
quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://localhost:5432/newsletter?ApplicationName=${postgreSQL-app-name}
    username: postgres
    password: admin